Removed routes.LowercaseUrls
- Due to MONO incompatibility, resulting in:
Error CS1061: Type `System.Web.Routing.RouteCollection' does not contain a definition for `LowercaseUrls' and no extension method `LowercaseUrls' of type `System.Web.Routing.RouteCollection' could be found. Are you missing an assembly reference? (CS1061) (AspNetMvcForMac)